title: Kelly Anran Zheng # your name (or website title) here
logo: "/images/Anran.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Urban Spatial Analytics
  <br><br>
  University of Pennsylvania
  <br><br>
  <a href="https://anranz.netlify.app/">My Academic Page</a>
  <br>
  <a href="https://anranz.netlify.app/uploads/resume.pdf">Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/anran-zheng-b214891b7/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
